services:
  app1:
    build: ./quiz-server
    deploy:
      replicas: 1 # Run two instances of the app (scalable)
    environment:
#      - APP_INSTANCE=${APP_INSTANCE:-default}
      - PORT=8080
    extra_hosts:
      - "localhost:192.168.0.101"
    networks:
      - app-network  # Define a custom network to allow communication

  app2:
    build: ./quiz-server
    deploy:
      replicas: 1 # Run two instances of the app (scalable)
    environment:
#      - APP_INSTANCE=${APP_INSTANCE:-default}
      - PORT=8080
    extra_hosts:
      - "localhost:192.168.0.101"
    networks:
      - app-network  # Define a custom network to allow communication


  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "8080:8080"  # Expose the load balancer on port 8080
      - "1918:1918"  # Expose the load balancer on port 8080
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Use the default bridge network driver